### ISSUE TITLE
Default setup not working

### ISSUE THREAD

**Issue by lesreaper** [mschmieder/python-kacl#13]
Using the latest `python-kacl` install, Python 3.7.3

There doesn't seem to be an example of how to start properly. Having never used versioning system with git, I followed these steps on a fresh branch with a `virtualenv` and a simple `pip install python-kacl`:
```
kacl-cli new CHANGELOG.md -> File created with default values
kacl-cli verify ->  "Success"
kacl-cli current -> returns null
kacl-cli add fixed 'We fixed some bad issues' --modify -> Adds new section to CHANGELOG.md called "fixed" with info
kacl-cli release 1.0.0 --auto-link
```
The last command returns a long error of which I will only return the end:
```
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/kacl/kacl_cli.py", line 253, in release
    kacl_changelog.release(version=version, link=link, auto_link=auto_link, increment=increment)
  File "/home/pi/.virtualenvs/test/lib/python3.7/site-packages/kacl/document.py", line 316, in release
    "previous_version": self.__versions[i+1].version(),
IndexError: list index out of range
```
Not sure what exactly to do from here. Doesn't seem I can create an initial version, or else I'm not using it properly. I added the Github config described at the bottom of the README as well. 

Am I way off base here?

**Comment by mschmieder** [comment]
Hi Richard,

I can confirm, this is a bug. the system tries to find a previously released version which obviously is not there. I'll have a look at it.

**Comment by mschmieder** [comment]
Please check the new version `python-kacl 0.2.21` it should fix the issue
