### ISSUE TITLE
[Feature Request] Pre-commit hook

### ISSUE THREAD

**Issue by Qu4tro** [mschmieder/python-kacl#18]
It would be nice to have a `pre-commit` hook, that could be used to run `kacl-cli verify`. 

Would you be open to a pull request that adds one to this repository? For reference, it should be adding a small file, like so:
`https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml`

Thanks.

**Comment by alfechner** [comment]
Opened PR for pre-commit hook config, see #19 .

**Comment by Qu4tro** [comment]
Wow, did not expected such a quick response. Thank you!

Left a couple of comments in the PR, but aside from those, it looks good to me!

**Comment by alfechner** [comment]
Yeah, I realised that we were looking into the pre-commit issue at exactly the same time.

**Comment by mschmieder** [comment]
Integrated
