### ISSUE TITLE
bug: kacl-cli removes blank line at the end of CHANGELOG.md

### ISSUE THREAD

**Issue by andreas-vester** [mschmieder/python-kacl#23]
When adding a new item to CHANGELOG.md via ``kacl-cli add`` or doing a new release via ``kacl_cli release``, the blank line at the end of the file will be removed.

Without a blank line at the end of CHANGELOG.md, my ``pre-commit`` hook "fix end of files" fails (id: end-of-file-fixer).

The automatic modification of CHANGELOG.md by ``kacl-cli`` shouldn't remove any blank line at the end of the file.

**Comment by mschmieder** [comment]
I will be looking into upgrading the CI and some other components with it and will fix this as well.

**Comment by mschmieder** [comment]
@andreas-vester this has been closed with `0.3.1`
