### ISSUE TITLE
Link reference case sensitivity

### ISSUE THREAD

**Issue by audrandessaint** [mschmieder/python-kacl#29]
I have noticed that the CHANGELOG from the [keep a changelog project](https://keepachangelog.com/en/1.0.0/) is considered invalid by the tool. This is because the tool is case-sensitive for link reference definitions.

In my opinion this is a bug because it goes against the [markdown specification](https://spec.commonmark.org/0.30), see [example 205](https://spec.commonmark.org/0.30/#example-205).

**Comment by mschmieder** [comment]
Hi,

I agree, this should not be case-sensitive. I'll be working on a new version as soon as possible.

**Comment by mschmieder** [comment]
@audrandessaint will be closed with https://gitlab.com/schmieder.matthias/python-kacl/-/merge_requests/new?merge_request%5Bsource_branch%5D=improved-verification

Please note that the project has been migrated to GitLab. I will setup the notice here in GitHub soon
