### ISSUE TITLE
Addition checks

### ISSUE THREAD

**Issue by audrandessaint** [mschmieder/python-kacl#30]
Here is a file that is considered valid by the tool:

```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

- Entry outside subsection

### Security

- Unordered subsection

### Changed

- Duplicate subsection

### Changed

- Duplicate subsection

[Unreleased]: ...
```

Some additional checks (making this file invalid) could be : 
- Every entry belongs to a subsection
- Subsections are always in the same order
- There are no duplicate subsections

**Comment by mschmieder** [comment]
@audrandessaint will be closed with https://gitlab.com/schmieder.matthias/python-kacl/-/merge_requests/new?merge_request%5Bsource_branch%5D=improved-verification

Please note that the project has been migrated to GitLab. I will setup the notice here in GitHub soon
